LOGGER_FORMAT = "%(asctime)s - %(name)s [%(levelname)s] %(message)s"
APP_LOG_LEVEL = "info"
TELEBOT_LOG_LEVEL = "warning"
SQLALCHEMY_ENGINE_LOG_LEVEL = "info"
MAX_CURRENCY_LEN = 25
CHANGE_CREDIT_PATTERN = r"([+-])(\d+) (\w+)бал"
POINTS_BURST_SIZE = 100
POINTS_REFILL_RATE = 100 / 60
MAX_BALLS_ROWS = 10
